export const maternalHealthChunks = [
  {
    id: "ayosehat-maternal-nutrition-overview",
    text: `Asupan gizi bagi ibu hamil perlu diperhatikan secara khusus karena penting bagi kesehatan ibu dan bayi. Agar proses kehamilan berjalan lancar dan melahirkan bayi yang sehat, sangat penting untuk memenuhi kebutuhan energi, protein, karbohidrat, vitamin, mineral, dan cairan (termasuk air), serta serat yang cukup. Baik dalam segi jumlah maupun kualitas makanan/minuman.`,
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "overview",
      target_group: "ibu_hamil_menyusui",
    },
  },
  {
    id: "ayosehat-maternal-nutrition-requirements",
    text: `Umumnya, perempuan usia 19-49 tahun membutuhkan energi sekitar 2150-2250 kkal dan protein 60 gram per hari. Namun pada ibu hamil yang normal, memerlukan tambahan energi 180-300 kkal dan protein 30 gram per hari. Untuk setiap penambahan berat badan 0,5 kg/minggu, ibu hamil (baik normal maupun yang Kekurangan Energi Kronis (KEK)) membutuhkan makanan tambahan untuk asupan energi sebesar 500 kkal/hari, dimana kurang dari 25% nya berasal dari protein.`,
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "kebutuhan_asupan",
      target_group: "ibu_hamil_menyusui",
      has_image: true,
      image_reference: ["ayosehat-maternal-nutrition-requirements-img-0"],
      base_energy: "2150-2250 kkal",
      additional_energy: "180-300 kkal",
      base_protein: "60 gram",
      additional_protein: "30 gram",
    },
  },
  {
    id: "ayosehat-maternal-nutrition-portions",
    text: `Ibu hamil membutuhkan makanan yang bervariasi dan kaya protein hewani, untuk tumbuh kembang janin. Berikut adalah porsi makan ideal ibu hamil:\n\nNASI ATAU MAKANAN POKOK\n- 5 porsi/hari untuk trimester 1.\n- 6 porsi/hari untuk trimester 2 dan 3.\n\nPROTEIN HEWANI\n- Ikan, telur, ayam, dan lainnya. 4 porsi/hari untuk semua trimester.\n\nPROTEIN NABATI\n- Tempe, tahu, dan lainnya. 4 porsi/hari untuk semua trimester.\n\nBUAH\n- 4 porsi/hari untuk semua trimester.\n\nSAYUR\n- 4 porsi/hari untuk semua trimester.\n\nTABLET TAMBAH DARAH\n- 1 Tablet Tambah Darah (TTD) setiap hari.\n\nJangan lupa minum air putih 8-12 gelas per hari untuk pencernaan dan mencegah dehidrasi.`,
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "porsi_makan",
      target_group: "ibu_hamil_menyusui",
      has_image: true,
      image_reference: ["ayosehat-maternal-nutrition-portions-img-0"],
      key_recommendations: [
        "pola_makan_bervariasi",
        "kaya_protein_hewani",
        "makan_sering_dalam_porsi_kecil",
        "hidrasi",
      ],
      related_links: [
        "https://ayosehat.kemkes.go.id/1000-hari-pertama-kehidupan/home",
      ],
    },
  },
  {
    id: "ayosehat-maternal-nutrition-supplements",
    text: `Makanan Tambahan bagi ibu hamil, adalah cemilan siap santap (contoh biskuit, dll) yang harus ditambahkan pada sajian makanan untuk ibu hamil yang mengalami Kekurangan Energi Kronis (KEK), setelah kebutuhan gizi dasarnya terpenuhi. Rekomendasi untuk pemberian makanan tambahan bagi ibu hamil adalah: Trimester 1: 2 keping biskuit; Trimester 2 & 3: 3 keping biskuit`,
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "makanan_tambahan",
      target_group: "ibu_hamil_menyusui",
      has_image: true,
      image_reference: ["ayosehat-maternal-nutrition-supplements-img-0"],
      condition: "KEK",
      recommendations_by_trimester: [
        "Trimester 1: 2 keping biskuit",
        "Trimester 2 & 3: 3 keping biskuit",
      ],
    },
  },
  {
    id: "ayosehat-maternal-nutrition-issues",
    text: "Masalah gizi yang sering terjadi pada ibu hamil adalah Kekurangan Energi Kronis (KEK), yaitu apabila kebutuhan gizi dasarnya tidak terpenuhi, ataupun mengalami kelelahan. KEK ditandai oleh rendahnya cadangan energi dalam waktu cukup lama, diukur dengan:\n➡️ Lingkar Lengan Atas kurang dari 23,5 cm\n➡️ Indeks Masa Tubuh Pra-Hamil - Trimester I di bawah 18,5 kg/m2",
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "masalah_gizi",
      target_group: "ibu_hamil_menyusui",

      measurement_criteria: [
        "Lingkar Lengan Atas < 23,5 cm",
        "IMT Pra-Hamil Trimester I < 18,5 kg/m2",
      ],
      related_links: [
        "https://ayosehat.kemkes.go.id/1000-hari-pertama-kehidupan/ragam-makanan-yang-mengandung-nutrisi-penting-bagi-ibu-hamil",
      ],
    },
  },
  {
    id: "ayosehat-maternal-nutrition-pregnancy-class",
    text: "Kelas Ibu Hamil adalah kelas di mana ibu hamil bisa mendapatkan informasi tentang kehamilan, persalinan, perawatan masa nifas, perawatan bayi baru lahir, kebutuhan dan pemenuhan gizi, serta pelayanan kesehatan yang diterima. Ibu hamil dan suami harus mengikuti kelas ini minimal 1x. Untuk dapat mengikuti Kelas Ibu Hamil, tanyakan pada petugas kesehatan mengenai jadwal dan tempat pelaksanaannya.",
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "kelas_ibu_hamil",
      target_group: "ibu_hamil_menyusui",

      recommendation: "Minimal mengikuti 1x",
    },
  },
  {
    id: "ayosehat-maternal-nutrition-tips",
    text: "Tips yang perlu dilakukan selama kehamilan, agar ibu dan janin selalu sehat dan terhindar dari kekurangan gizi:\n\n*Periksa kehamilan & makan teratur*\n1. Lakukan pemeriksaan kehamilan rutin\n2. Makan 3 kali makanan utama ditambah dengan 1-2 kali makanan selingan dalam sehari, sesuai anjuran.\n\n*Penuhi kebutuhan tubuh*\n3. Konsumsi Tablet Tambah Darah (TTD) atau suplementasi zat gizi mikro lainnya\n4. Cukup konsumsi air putih\n5. Mengkonsumsi garam beryodium\n\n*Konsumsi makanan tambahan*\n6. Konsumsi makanan dalam porsi kecil tapi sering. Buah dan sayur harus masuk dalam menu sehari-hari.\n7. Mengonsumsi makanan tambahan\n8. Membatasi konsumsi kopi atau minuman berkafein lainnya\n\n*Batasi makan makanan tertentu*\n9. Membatasi konsumsi makanan yang tinggi gula, garam, dan lemak\n10. Menghindari konsumsi makanan yang merangsang pencernaan\n11. Rutin memantau pertambahan berat badan.\n12. Cukup istirahat.\n13. Hidup bersih dan sehat.\n\nJika ada kendala dalam menjaga kesehatan kehamilan atau pertanyaan lebih lanjut, datang ke fasilitas layanan kesehatan untuk konsultasi ke tenaga kesehatan.",
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "tips",
      target_group: "ibu_hamil_menyusui",

      key_recommendations: [
        "pemeriksaan_rutin",
        "makan_teratur",
        "suplementasi_TTD",
        "hidrasi_cukup",
        "konsumsi_garam_beryodium",
        "porsi_kecil_dan_sering",
        "makanan_tinggi_gizi",
        "batasi_gula_garam_lemak",
        "hidup_bersih_dan_sehat",
      ],
    },
  },
  {
    id: "ayosehat-maternal-recipe-nasi-rawon",
    text: "Nasi Rawon\nRESEP UNTUK\n3 PORSI\n\nInformasi nilai gizi per porsi :\nEnergi 698 kkal\nProtein 36 gr\nLemak 27.9 gr\n*resep ini berkontribusi energi sebesar 29,3% dari kebutuhan gizi sehari\n\n*Cara Membuat*\nMasak daging bersama daun jeruk, serai, laos dan daun salam sampai empuk dan matang. Angkat daging, lalu potong kecil-kecil. Saring rebusan, didihkan lagi bersama irisan daging. Panaskan minyak, tumis bumbu halus sampai harum dan matang. Angkat, lalu masukkan ke dalam rebusan daging. Masak dengan api kecil sampai mendidih kembali. Sajikan rawon, tauge pendek, tempe goreng, telur asin dan kerupuk udang. Jangan lupa nasinya.",
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "resep",
      target_group: "ibu_hamil_menyusui",
      has_image: true,
      image_reference: ["ayosehat-maternal-recipe-nasi-rawon-img-0"],
      ingredients: [
        "nasi",
        "daging sapi",
        "tempe",
        "tauge",
        "telur asin",
        "minyak goreng",
        "kerupuk udang",
        "kaldu daging",
        "serai",
        "daun jeruk",
        "daun salam",
        "laos",
        "bawang merah",
        "bawang putih",
        "air asam jawa",
        "jahe",
        "kunyit",
        "kluwek",
        "ketumbar",
        "garam",
        "gula pasir",
        "kaldu jamur",
        "jeruk",
      ],
    },
  },
  {
    id: "ayosehat-maternal-recipe-lapis-tamie-isi-ayam",
    text: "Lapis Tamie Isi Ayam\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 527 kkal\nProtein 25.3 gr\nLemak 22.9 gr\n\n*Cara Membuat*\n1. Tumis bumbu halus sampai harum, masukkan ayam cincang dan masak sampai berubah warna.\n2. Tambahkan saus tiram, minyak wijen, garam, dan merica secukupnya. Koreksi rasa dan sisihkan.\n3. Didihkan kurang lebih 1.5 liter air, tambahkan 1 sdm minyak goreng atau mentega.\n4. Campurkan tahu, mie kering rebus, wortel, keju, tepung terigu, tepung tapioka, garam, merica, kaldu jamur jika dibutuhkan, bawang merah, bawang putih goreng halus, bawang daun, dan seledri. Uleni sampai tercampur merata.\n5. Ambil 1.5 sendok makan adonan, pipihkan dan isi tumisan ayam cincang. Bentuk bulat lonjong atau sesuai selera.\n6. Masukkan ke dalam air mendidih dan masak sampai matang atau mengapung.\n7. Siapkan loyang yang sudah diolesi minyak. Ratakan sebagian adonan, tambahkan isian ayam, dan tutup kembali dengan adonan tahu.\n8. Kukus selama 25 menit atau sampai matang.\n9. Dinginkan terlebih dahulu sebelum dipotong-potong.\n10. Campurkan tepung terigu, garam, dan air hingga merata. Gulirkan potongan tamie ke dalam larutan tepung, lalu ke tepung panir.\n11. Dinginkan di kulkas atau freezer sebelum digoreng.\n12. Goreng di minyak panas hingga kuning keemasan. Sajikan selagi hangat dengan saus sambal jika diinginkan.",
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "resep",
      target_group: "ibu_hamil_menyusui",
      has_image: true,
      image_reference: [
        "ayosehat-maternal-recipe-lapis-tamie-isi-ayam-img-0",
        "ayosehat-maternal-recipe-lapis-tamie-isi-ayam-img-1",
      ],
    },
    ingredients: [
      "tahu putih",
      "daging ayam",
      "telur ayam",
      "tepung tapioka",
      "tepung terigu",
      "mie kering",
      "keju parut",
      "wortel",
      "daun bawang",
      "daun seledri",
      "bawang putih goreng",
      "bawang goreng",
      "garam",
      "merica",
      "kaldu jamur",
      "saus tiram",
      "minyak wijen",
      "pepaya",
      "bawang merah",
      "bawang putih",
      "tepung panir",
      "air",
      "minyak goreng",
      "mentega",
    ],
  },
  {
    id: "ayosehat-maternal-recipe-siomay-ayam-udang-komplit",
    text: "Siomay Ayam Udang Komplit\n\nRESEP UNTUK 3 PORSI\n\n*Cara Membuat Siomay*\n1. Campur ayam cincang, udang cincang, dan semua bumbu. Uleni hingga merata.\n2. Tambahkan air es secara perlahan sambil terus diuleni. Masukkan tepung terigu, tepung tapioka, dan maizena, aduk hingga tercampur rata.\n3. Ambil 1 lembar kulit pangsit, isi dengan 1 sendok makan adonan, dan lakukan hingga adonan habis.\n4. Kukus siomay hingga matang.\n\n*Cara Membuat Bumbu Kacang*\n1. Haluskan kacang goreng, bawang, dan cabe keriting.\n2. Masak kacang halus, tambahkan air, daun jeruk, air asam jawa, dan minyak goreng.\n3. Sajikan siomay dengan tahu, pare, telur rebus, kentang, dan beri bumbu kacang, kecap manis, dan bawang goreng di atasnya.",
    metadata: {
      source: "ayosehat",
      category: "maternal_health",
      topic: "gizi",
      subtopic: "resep",
      target_group: "ibu_hamil_menyusui",
    },
    ingredients: [
      "garam",
      "gula pasir",
      "minyak wijen",
      "bawang putih goreng",
      "bawang merah goreng",
      "kaldu jamur",
      "merica",
      "ayam cincang",
      "udang cincang",
      "air es",
      "tepung tapioka",
      "tepung terigu",
      "maizena",
      "baking powder",
      "kulit pangsit",
      "tahu putih",
      "pare",
      "kentang",
      "telur rebus",
      "kacang tanah",
      "cabe keriting",
      "daun jeruk",
      "air asam jawa",
      "kecap manis",
      "minyak goreng",
      "melon",
    ],
  },
  {
    "id": "ayosehat-maternal-recipe-liwet-ikan-goreng-kari-daun-singkong-ebi",
    "text": "Liwet Ikan Goreng dan Kari Daun Singkong dan Ebi\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 635 kkal\nProtein 42.9 gr\nLemak 26.0 gr\n\n*Cara Membuat Nasi Liwet*\n1. Tumis bawang merah dan bawang putih hingga harum.\n2. Masukkan daun salam, sereh, daun jeruk, cabai rawit, dan laos. Tumis sebentar.\n3. Tambahkan beras dan aduk rata. Masukkan kaldu ayam dan garam secukupnya.\n4. Masak nasi hingga matang.\n\n*Cara Membuat Ikan Goreng*\n1. Lumuri ikan nila dengan bawang putih, jeruk nipis, dan garam. Diamkan sebentar.\n2. Goreng ikan hingga matang dan kecokelatan.\n\n*Cara Membuat Tumis Daun Singkong*\n1. Tumis bumbu halus hingga harum.\n2. Masukkan daun salam, serai, daun singkong, dan santan. Aduk rata.\n3. Tambahkan teri medan goreng, garam, dan gula pasir. Masak hingga daun singkong matang.\n\n*Sajikan nasi liwet dengan ikan goreng dan tumis daun singkong.*",
    "metadata": {
        "source": "ayosehat",
        "category": "maternal_health",
        "topic": "gizi",
        "subtopic": "resep",
        "target_group": "ibu_hamil_menyusui",
        "has_image": true,
        "image_reference": [
            "ayosehat-maternal-recipe-liwet-ikan-goreng-kari-daun-singkong-ebi-img-0",
            "ayosehat-maternal-recipe-liwet-ikan-goreng-kari-daun-singkong-ebi-img-1"
        ]
    },
    "ingredients": [
        "beras",
        "bawang merah",
        "bawang putih",
        "daun salam",
        "sereh",
        "daun jeruk",
        "cabai rawit hijau",
        "laos",
        "garam",
        "kaldu ayam",
        "minyak goreng",
        "ikan nila",
        "jeruk nipis",
        "daun singkong",
        "lengkuas",
        "terasi",
        "teri medan",
        "gula pasir",
        "santan",
        "bawang merah",
        "cabai merah keriting",
        "cabai rawit",
        "kemiri",
        "kunyit",
        "belimbing"
    ]
},
{
  "id": "nasi-kuning-harum-rampa-ikan-tuna-balado",
  "text": "Nasi Kuning Harum Rampa Ikan Tuna Balado\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 691 kkal\nProtein 34.9 gr\nLemak 26.9 gr\n\n*Cara Membuat*\n1. Cuci beras dan ketan sampai bersih kemudian rendam dalam air selama 15-20 menit, kemudian tiriskan.\n2. Tumis bumbu yang sudah dihaluskan dengan sedikit minyak.\n3. Tambahkan santan, beras ketan, tumisan bumbu halus, garam, dan semua bumbu rempah di masak dengan api sedang sampai menjadi aron nasi, jangan lupa di aduk-aduk, koreksi rasa.\n4. Kukus aron nasi uduk, kurang lebih selama 30 menit.",
  "metadata": {
    "source": "ayosehat",
    "category": "maternal_health",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "ibu_hamil_menyusui",
    "has_image": true,
    "image_reference": [
      "nasi-kuning-harum-rampa-ikan-tuna-balado-img-0",
      "nasi-kuning-harum-rampa-ikan-tuna-balado-img-1"
    ]
  },
  "ingredients": [
    "beras",
    "beras ketan",
    "santan cair",
    "daun salam",
    "daun pandan",
    "sereh",
    "kunyit",
    "kayu manis",
    "jahe",
    "bunga lawang",
    "kapulaga",
    "merica",
    "cabe merah",
    "bawang merah",
    "bawang putih",
    "ikan tongkol",
    "tahu",
    "udang",
    "kacang panjang",
    "wortel",
    "tomat",
    "jeruk",
    "jantung pisang",
    "melinjo",
    "teri medan",
    "cabe hijau",
    "laos",
    "kaldu jamur",
    "semangka"
  ]
},
{
  "id": "bola-bola-nasi-rabuk-ikan",
  "text": "Bola-bola Nasi Rabuk Ikan\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 468 kkal\nProtein 14.4 gr\nLemak 17.4 gr\n\n*Cara Membuat*\n1. Tumis bawang dengan minyak hingga layu, kemudian masukkan sayuran (wortel, buncis dan jagung). Masak hingga setengah matang, lalu angkat.\n2. Tambahkan nasi, terigu, telur, bawang putih goreng, bawang merah goreng, daun bawang, lada, garam, dan kaldu bubuk secukupnya, aduk hingga rata dan kalis.\n3. Ambil sedikit nasi, pipihkan di tangan. Isi dengan rabuk ikan lalu bentuk bulat.\n4. Lumuri dengan terigu, celupkan ke telur kocok dan gulingkan ke tepung roti/panir. Diamkan minimal 1 jam atau simpan dalam lemari es.\n5. Panaskan minyak lalu goreng hingga berwarna kecoklatan.",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "umur-2---5-tahun",
    "has_image": true,
    "image_reference": [
      "bola-bola-nasi-rabuk-ikan-img-0"
    ]
  },
  "ingredients": [
    "beras",
    "minyak sayur",
    "buncis",
    "wortel",
    "jagung pipil",
    "tepung terigu",
    "telur ayam",
    "rabuk ikan",
    "bawang bombay",
    "bawang putih goreng",
    "bawang merah goreng",
    "daun bawang",
    "lada",
    "garam",
    "kaldu jamur",
    "tepung roti",
    "buah naga"
  ]
},
{
  "id": "nasi-masak-ayam-kecap-sayur",
  "text": "Nasi Masak Ayam Kecap Sayur\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 424 kkal\nProtein 22.9 gr\nLemak 18.1 gr\n\n*Cara Membuat*\n1. Masukkan minyak ke dalam wajan. Tumis bawang putih hingga harum.\n2. Masukkan bawang bombay, aduk rata.\n3. Masukkan ayam, masak hingga berubah warna.\n4. Tambahkan tahu, telur puyuh rebus dan pakcoy, kecap manis, gula, garam, merica, dan air. Aduk rata hingga matang.\n5. Masukkan daun bawang, aduk rata.\n6. Angkat dan sajikan.",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "umur-2---5-tahun",
    "has_image": true,
    "image_reference": [
      "nasi-masak-ayam-kecap-sayur-img-0"
    ]
  },
  "ingredients": [
    "nasi putih",
    "dada ayam filet",
    "telur puyuh rebus",
    "tahu putih",
    "pakcoy",
    "kecap manis",
    "air",
    "minyak",
    "bawang putih",
    "bawang bombay",
    "daun bawang",
    "garam",
    "gula",
    "merica",
    "jeruk"
  ]
},
{
  "id": "nasi-sup-tabas-udang-sayur",
  "text": "Nasi Sup Tabas Udang Sayur\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 537 kkal\nProtein 23.4 gr\nLemak 18.9 gr\n\n*Bumbu Halus*\n- 2 siung bawang merah\n- 1 siung bawang putih\n- 10 gr (1 sdm) minyak untuk menumis\n\n*Cara Membuat*\n1. Campurkan ikan tenggiri cincang, tepung tapioka, bawang daun, bawang merah goreng halus, bawang putih goreng, saos tiram, garam, merica, gula, dan putih telur hingga merata dan adonan bisa dibentuk.\n2. Ambil tahu yang sudah dilubangi bagian tengahnya, isi dengan 1 sendok makan adonan ikan. Lakukan hingga selesai.\n3. Kukus baso tahu selama 15-20 menit.\n4. Tumis bumbu halus hingga harum, tambahkan air kaldu ayam atau udang, masak hingga mendidih.\n5. Masukkan udang dan wortel, tambahkan kecap ikan, saos tiram, garam, merica, dan gula secukupnya. Koreksi rasa sebelum api dimatikan.\n6. Masukkan tahu baso, pakcoy, dan soun ke dalam mangkuk saji.\n7. Siram dengan kuah udang dan wortel, tambahkan bawang goreng, seledri, dan bawang daun di atasnya.\n8. Sajikan dengan nasi hangat dan lengkapi dengan buah.",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "umur-2---5-tahun",
    "has_image": true,
    "image_reference": [
      "nasi-sup-tabas-udang-sayur-img-0"
    ]
  },
  "ingredients": [
    "nasi putih",
    "ikan tenggiri cincang",
    "putih telur",
    "tepung tapioka",
    "tahu",
    "bawang daun",
    "bawang merah goreng",
    "bawang putih goreng",
    "saos tiram",
    "minyak wijen",
    "garam",
    "merica",
    "udang rebus",
    "air kaldu udang",
    "pokcoy",
    "soun",
    "wortel",
    "kecap ikan",
    "seledri",
    "bawang goreng",
    "jahe",
    "semangka",
    "bawang merah",
    "bawang putih",
    "minyak untuk menumis",
    "gula"
  ]
},
{
  "id": "nasi-bakar-ayam-santan",
  "text": "Nasi Bakar Ayam Santan\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 421 kkal\nProtein 18.2 gr\nLemak 18.2 gr\n\n*Bumbu Halus*\n- 6 siung bawang merah\n- 4 siung bawang putih\n- 1 sdt ketumbar\n- 4 buah kemiri\n- 0.5 sdt jintan\n- Garam secukupnya\n- Merica secukupnya\n- Gula secukupnya\n- Kaldu jamur secukupnya\n- 20 gr (2 sdm) minyak goreng\n\n*Bahan Nasi Gurih*\n- 150 gr (15 sdm) beras putih\n- 5 gr (1 sdt) bawang putih goreng\n- 5 gr (1 sdt) bawang merah goreng\n- 10 gr (1 sdm) margarin\n- 1 lembar daun jeruk\n- 1 lembar daun salam\n- 1 batang serai\n- 1 lembar daun pandan\n- Garam secukupnya\n\n*Bahan Campuran*\n- 120 gr (12 sdm) filet dada ayam, potong kotak\n- 60 gr (3 potong) tahu, potong kotak\n- 60 gr (6 ekor) udang\n- 30 gr (3 sdm) daun bayam\n- 30 gr (3 sdm) wortel\n- 50 ml (5 sdm) santan kental\n- 1 lembar daun salam\n- 1 batang serai\n- 2 lembar daun jeruk\n- 1 cm jahe\n\n*Buah*\n- 300 gr buah pepaya\n\n*Cara Membuat*\n1. Tumis bumbu halus hingga harum.\n2. Masak nasi gurih dengan menambahkan bahan nasi gurih ke dalam panci hingga matang.\n3. Campurkan bahan campuran dengan bumbu halus yang sudah ditumis.\n4. Kukus campuran hingga matang.\n5. Bungkus campuran dengan daun pisang dan bakar hingga harum.\n6. Sajikan dengan nasi gurih dan buah pepaya.",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "umur-2---5-tahun",
    "has_image": true,
    "image_reference": [
      "nasi-bakar-ayam-santan-img-0"
    ]
  },
  "ingredients": [
    "beras putih",
    "bawang putih goreng",
    "bawang merah goreng",
    "margarin",
    "daun jeruk",
    "daun salam",
    "serai",
    "daun pandan",
    "garam",
    "filet dada ayam",
    "tahu",
    "udang",
    "daun bayam",
    "wortel",
    "santan kental",
    "kemiri",
    "ketumbar",
    "jintan",
    "gula",
    "kaldu jamur",
    "minyak goreng",
    "pepaya"
  ]
},
{
  "id": "nugget-tempe-ayam-sayuran",
  "text": "Nugget Tempe Ayam Sayuran\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 191 kkal\nProtein 10.5 gr\nLemak 9.0 gr\n\n*Bahan*\n- 200 gr tempe di potong kotak kecil, kukus\n- 100 gr daging ayam cincang, haluskan\n- 100 gr (2 butir) telur ayam, kocok\n- 50 gr (5 sdm) wortel\n- 50 gr (5 sdm) keju parut\n- 10 gr (1 batang) bawang daun, iris halus\n- 10 gr (1 sdm) bawang goreng halus\n- 10 gr (1 sdm) bawang putih halus\n- 20 gr (2 sdm) tepung terigu\n- 20 gr (2 sdm) tepung tapioka\n\n*Bahan Pelapis*\n- 30 gr (3 sdm) tepung terigu\n- 100 ml air atau secukupnya\n- 100 gr (10 sdm) tepung panir\n- Minyak untuk menggoreng secukupnya\n\n*Buah*\n- 270 gr buah semangka\n\n*Cara Membuat*\n1. Campurkan tempe, daging ayam cincang, wortel, keju, bawang daun, tepung terigu, tapioka, telur, bawang goreng, dan bawang putih halus. Aduk sampai tercampur rata.\n2. Ambil loyang olesi minyak dulu kemudian masukkan adonan nugget dan ratakan.\n3. Kukus selama 30 menit atau sampai matang. Setelah dingin, potong adonan sesuai selera.\n4. Cairkan terigu dengan air sampai menjadi larutan yang agak kental.\n5. Celupkan nugget ke tepung terigu basah, lalu gulingkan ke tepung panir.\n6. Sebaiknya disimpan dulu di kulkas selama 30 menit.\n7. Atau bisa langsung digoreng di minyak yang panas.\n8. Sajikan selagi hangat.\n\nBisa juga dijadikan lauk.",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "bayi-usia-12---23-tahun",
    "has_image": true,
    "image_reference": [
      "nugget-tempe-ayam-sayuran-img-0"
    ]
  },
  "ingredients": [
    "tempe",
    "daging ayam cincang",
    "telur ayam",
    "wortel",
    "keju parut",
    "bawang daun",
    "bawang goreng halus",
    "bawang putih halus",
    "tepung terigu",
    "tepung tapioka",
    "tepung panir",
    "minyak untuk menggoreng",
    "semangka"
  ]
},
{
  "id": "nasi-ikan-kuah-kuning",
  "text": "Nasi Ikan Kuah Kuning\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 267 kkal\nProtein 28.5 gr\nLemak 10.7 gr\n\n*Bahan*\n- 150 gr (15 sdm) nasi\n- 360 gr (3 ekor) ikan kembung\n- 75 gr (7.5 sdm) labu siam\n- 75 gr (7.5 sdm) tempe\n- 60 gr (1 buah besar) tomat besar\n- 15 ml (1 sdm) minyak goreng\n\n*Bumbu*\n- 2 lembar daun salam\n- 1 batang sereh digeprek\n- 2 cm laos digeprek\n- Garam secukupnya\n- Gula secukupnya\n- 35 ml (3.5 sdm) santan\n- 750 ml air\n- 2 buah jeruk nipis\n\n*Bumbu Halus*\n- 5 siung bawang merah\n- 3 siung bawang putih\n- 3 buah kemiri\n- 2 cm jahe\n- 2 cm kunyit\n\n*Buah*\n- 270 gr semangka\n\n*Cara Membuat*\n1. Bersihkan ikan, lumuri dengan garam dan jeruk nipis atau cuka biarkan 10 menit, kemudian bilas dengan air sampai bersih.\n2. Lumuri kembali ikan kembung dengan garam dan jeruk nipis biarkan 5 menit.\n3. Panaskan minyak, goreng ikan kembung sampai matang dan sisihkan.\n4. Tumis bumbu halus tambahkan sereh, salam, dan laos tumis sampai air menyusut.\n5. Masukkan potongan labu siam dan tempe masak sampai matang.\n6. Tambahkan air, santan, dan masukkan ikan goreng.\n7. Tambahkan garam dan gula secukupnya, masukkan tomat dan koreksi rasa. Sajikan dengan nasi hangat.",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "bayi-usia-12---23-tahun",
    "has_image": true,
    "image_reference": [
      "nasi-ikan-kuah-kuning-img-0"
    ]
  },
  "ingredients": [
    "nasi",
    "ikan kembung",
    "labu siam",
    "tempe",
    "tomat besar",
    "minyak goreng",
    "daun salam",
    "sereh",
    "laos",
    "garam",
    "gula",
    "santan",
    "air",
    "jeruk nipis",
    "bawang merah",
    "bawang putih",
    "kemiri",
    "jahe",
    "kunyit",
    "semangka"
  ]
},
{
  "id": "sup-telur-puyuh-ikan-air-tawar-labu-kuning",
  "text": "Sup Telur Puyuh Ikan Air Tawar Labu Kuning\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 261 kkal\nProtein 13.6 gr\nLemak 9.1 gr\n\n*Cara Membuat*\n1. Rebus kaldu ayam hingga mendidih, masukkan kentang, kacang merah, dan labu kuning hingga setengah matang.\n2. Masukkan suwiran ikan nila kukus, bawang merah goreng, dan bawang putih goreng, masak hingga matang.\n3. Tambahkan tomat, bawang daun, bawang goreng, dan telur puyuh, aduk perlahan.\n4. Tambahkan garam, gula, dan merica secukupnya dan aduk rata. Angkat dan sajikan dengan buah.\n\n*Bahan*\n- 150 gr (15 sdm) nasi putih\n- 70 gr (7 sdm) kentang, potong dadu\n- 50 gr (5 sdm) labu kuning, potong dadu\n- 120 gr (12 sdm) ikan nila kukus, disuwir\n- 60 gr (6 butir) telur puyuh, rebus\n- 15 gr (3 sdt) kacang merah\n- 45 gr (4.5 sdm) tomat, potong dadu\n- 10 gr (1 batang) bawang daun\n- 5 gr (1 sdt) bawang merah goreng\n- 5 gr (1 sdt) bawang putih goreng\n- 150 ml kaldu ayam\n- Garam, gula, merica secukupnya\n\n*Buah*\n- 150 gr (6 potong) pepaya",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "bayi-usia-12---23-tahun",
    "has_image": false,
    "image_reference": []
  },
  "ingredients": [
    "nasi putih",
    "kentang",
    "labu kuning",
    "ikan nila kukus",
    "telur puyuh",
    "kacang merah",
    "tomat",
    "bawang daun",
    "bawang merah goreng",
    "bawang putih goreng",
    "kaldu ayam",
    "garam",
    "gula",
    "merica",
    "pepaya"
  ]
},
{
  "id": "nasi-soto-ayam-kuah-kuning",
  "text": "Nasi Soto Ayam Kuah Kuning\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 263 kkal\nProtein 9.5 gr\nLemak 10.9 gr\n\n*Cara Membuat*\n1. Rebus ayam hingga setengah matang, tambahkan serai geprek, daun salam, daun jeruk, dan lengkuas yang digeprek.\n2. Tumis bumbu yang dihaluskan hingga harum dan matang, lalu masukkan ke dalam rebusan ayam.\n3. Tambahkan garam, gula, dan merica. Masak hingga ayam matang dan empuk (jangan lupa koreksi rasa).\n4. Angkat ayam dan suir-suir (shred the chicken).\n5. Siapkan mangkuk dengan soun yang sudah direndam, toge, suiran daging ayam, serta telur puyuh rebus.\n6. Tambahkan kuah soto ayam, dan taburkan daun bawang, seledri, dan bawang goreng.\n7. Sajikan dengan nasi hangat dan lengkapi dengan buah.\n\n*Bahan*\n- 150 gr (15 sdm) nasi\n- 100 gr (2 potong) ayam dengan tulang\n- 10 gr (1 sdm) soun\n- 60 gr (6 butir) telur puyuh, rebus\n- 30 gr (3 sdm) toge\n- 10 gr (1 sdm) minyak goreng\n\n*Bumbu*\n- 1 lembar daun salam\n- 1 batang serai, digeprek\n- 1 lembar daun jeruk\n- 1/2 cm lengkuas, digeprek\n- 1500 ml air untuk merebus\n- Garam dan gula secukupnya\n- Merica secukupnya\n\n*Bumbu Halus*\n- 1 butir kemiri\n- 1 siung bawang merah\n- 1 siung bawang putih\n- 1/2 cm jahe\n- 1/2 cm kunyit\n- 1/4 sdt jinten\n- 1/2 sdt ketumbar\n\n*Pelengkap*\n- 1/2 sdt irisan daun bawang\n- 1/2 sdt irisan seledri\n- 1/3 sdt irisan bawang goreng",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "bayi-usia-12---23-tahun",
    "has_image": false,
    "image_reference": []
  },
  "ingredients": [
    "nasi",
    "ayam",
    "soun",
    "telur puyuh",
    "toge",
    "minyak goreng",
    "daun salam",
    "serai",
    "daun jeruk",
    "lengkuas",
    "air",
    "garam",
    "gula",
    "merica",
    "kemiri",
    "bawang merah",
    "bawang putih",
    "jahe",
    "kunyit",
    "jinten",
    "ketumbar",
    "daun bawang",
    "seledri",
    "bawang goreng"
  ]
},
{
  "id": "nasi-sup-telur-puyuh-bola-tahu-ayam",
  "text": "Nasi Sup Telur Puyuh Bola Tahu Ayam\n\nRESEP UNTUK 3 PORSI\n\nInformasi nilai gizi per porsi:\nEnergi 260 kkal\nProtein 10.4 gr\nLemak 10.7 gr\n\n*Cara Membuat*\n1. Rebus air sampai mendidih.\n2. Sambil menunggu, campurkan tahu, daging ayam cincang, bumbu halus, garam, gula, dan merica. Haluskan dan tambahkan tepung tapioka, lalu uleni hingga tercampur rata dan bisa dibentuk.\n3. Ambil adonan sebanyak satu sendok teh, bentuk bulat, dan masukkan langsung ke dalam air mendidih.\n4. Lakukan sampai adonan habis.\n5. Setelah semua bola-bola tahu ayam mengapung, masukkan wortel dan jagung terlebih dahulu, lalu tambahkan brokoli dan telur puyuh rebus.\n6. Masukkan garam, gula, merica, serta irisan daun bawang dan seledri. Koreksi rasa setelah sayuran matang.\n7. Sajikan dengan nasi dan taburan bawang goreng.\n\n*Bahan*\n- 150 gr (15 sdm) nasi putih\n- 45 gr (1 potong kecil) tahu putih\n- 60 gr (5 sdm) daging ayam cincang\n- 60 gr (6 butir) telur puyuh, rebus\n- 30 gr (3 sdm) wortel\n- 30 gr (3 sdm) jagung pipil kuning\n- 30 gr (3 sdm) brokoli\n- Air secukupnya\n\n*Bahan Tambahan*\n- 10 gr (1 batang) seledri, diiris\n- 10 gr (1 batang) daun bawang, diiris\n- 15 gr (1.5 sdm) tepung tapioka\n- Garam secukupnya\n- Gula secukupnya\n- Merica secukupnya\n- 10 gr (1 sdm) bawang goreng\n\n*Buah*\n- 135 gr (3 potong) melon",
  "metadata": {
    "source": "ayosehat",
    "category": "child_nutrition",
    "topic": "gizi",
    "subtopic": "resep",
    "target_group": "bayi-usia-12---23-tahun",
    "has_image": false,
    "image_reference": []
  },
  "ingredients": [
    "nasi putih",
    "tahu putih",
    "daging ayam cincang",
    "telur puyuh",
    "wortel",
    "jagung pipil kuning",
    "brokoli",
    "air",
    "seledri",
    "daun bawang",
    "tepung tapioka",
    "garam",
    "gula",
    "merica",
    "bawang goreng",
    "melon"
  ]
}
];
